apiVersion: v1
kind: Service
metadata:
  name: "{{ template "wqdss.fullname" . }}-model-registry"
  labels:
{{ include "wqdss.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: "{{ template "wqdss.fullname" . }}-model-registry"
    app.kubernetes.io/instance: {{ .Release.Name }}
