apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: model-exec
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1beta2
    kind: Deployment
    name: model-exec
  targetCPUUtilizationPercentage: 80
